name: Upload Personalized Page

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate personalized page
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PICTURE: ${{ secrets.USER_PICTURE }}
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Personalisierte Seite von ${USER_NAME}</title>
              <link rel="stylesheet" href="style.css">
          </head>
          <body>
              <h1>Willkommen, ${USER_NAME}!</h1>
              <img src="${USER_PICTURE}" alt="User Picture">
          </body>
          </html>' > personalized_page.html

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add personalized_page.html
          git commit -m 'Add personalized page'
          git push
